#!/bin/bash

ROS_DISTRO=kinetic

./install

EXTRA_PACKAGES="ompl octomap_ros octomap_msgs dynamic_edt_3d multimaster_fkie node_manager_fkie master_discovery_fkie"
WS=extra_ros_packages_ws

if [ -d "$WS" ]; then
  rm -rf "$WS"
fi
mkdir -p $WS/src
pushd $WS/src
wstool init

popd
pushd $WS

rosinstall_generator ${EXTRA_PACKAGES} --rosdistro kinetic  --deps --wet-only --tar --exclude RPP > extra_packages.rosinstall
rosinstall_generator fcl --rosdistro indigo  --deps --wet-only --tar --exclude RPP > fcl.rosinstall

wstool merge extra_packages.rosinstall -t src
wstool merge fcl.rosinstall -t src

pushd src

wstool update -j8

popd

#patch ompl to link LZ4 Library
patch -p4 < patches/patch_ompl.diff

rosdep -r install --from-paths src --ignore-src --rosdistro kinetic -y --skip-keys="python-qt-bindings-qwt5 libqt5-core libqt5-gui libqt5-opengl libqt5-opengl-dev libqt5-widgets qt5-qmake qtbase5-dev python-imaging python-qt5-bindings python-qt5-bindings-gl python-qt5-bindings-webkit"

catkin config --extend /opt/ros/kinetic --install  --install-space /opt/ros/kinetic --cmake-args \
  -DCATKIN_ENABLE_TESTING=1 \
  -DCMAKE_BUILD_TYPE=Release \
  -DPYTHON_LIBRARY=$(python -c "import sys; print sys.prefix")/lib/libpython2.7.dylib \
  -DPYTHON_INCLUDE_DIR=$(python -c "import sys; print sys.prefix")/include/python2.7 \
  -DCMAKE_FIND_FRAMEWORK=LAST

#catkin build --limit-status-rate 1
