#!/bin/bash

# Installs some ROS extra packages relevant to ASL
ROS_DISTRO=${ROS_DISTRO:-kinetic}
ROS_CONFIGURATION=${ROS_CONFIGURATION:-desktop_full}
ROS_INSTALL_DIR=${ROS_INSTALL_DIR:-/opt/ros/${ROS_DISTRO}}

# The following should probably have been done by the user.
# We add this line here just to be sure.
#. ${ROS_INSTALL_DIR}/setup.bash

EXTRA_PACKAGES="ompl octomap_ros octomap_msgs dynamic_edt_3d multimaster_fkie node_manager_fkie master_discovery_fkie"
WS=extra_ros_packages_ws

if [ -d "$WS" ]; then
  rm -rf "$WS"
fi
mkdir $WS
pushd $WS

rosinstall_generator ${EXTRA_PACKAGES} --rosdistro kinetic  --deps --wet-only --tar --exclude RPP > extra_packages.rosinstall

wstool init -j8 src extra_packages.rosinstall

pushd src
wstool update -j8
popd

#patch ompl to link LZ4 Library
curl https://raw.githubusercontent.com/fmina/ros-kinetic-install-osx/master/patches/patch_ompl.diff | patch

rosdep -r install --from-paths src --ignore-src --rosdistro kinetic -y --skip-keys="python-qt-bindings-qwt5 libqt5-core libqt5-gui libqt5-opengl libqt5-opengl-dev libqt5-widgets qt5-qmake qtbase5-dev python-imaging python-qt5-bindings python-qt5-bindings-gl python-qt5-bindings-webkit"

catkin config --extend /opt/ros/kinetic --install  --install-space /opt/ros/kinetic --cmake-args \
  -DCATKIN_ENABLE_TESTING=1 \
  -DCMAKE_BUILD_TYPE=Release \
  -DPYTHON_LIBRARY=$(python -c "import sys; print sys.prefix")/lib/libpython2.7.dylib \
  -DPYTHON_INCLUDE_DIR=$(python -c "import sys; print sys.prefix")/include/python2.7 \
  -DCMAKE_FIND_FRAMEWORK=LAST

catkin build --limit-status-rate 1

popd
